# Generated by Django 2.1.15 on 2021-01-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticproduct',
            name='targetgrossprofit',
            field=models.IntegerField(blank=True, default=33, null=True, verbose_name='Target Gross Profit (in %)'),
        ),
        migrations.AlterField(
            model_name='importsproduct',
            name='targetgrossprofit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Target Gross Profit (in %)'),
        ),
    ]
