# Generated by Django 2.1.15 on 2021-01-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210113_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='addimportsitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
