# Generated by Django 2.1.15 on 2021-01-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210122_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticitem',
            name='baseproductsalesprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Base Product Sales Price C$'),
        ),
        migrations.AlterField(
            model_name='adddomesticitem',
            name='productcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Product Cost C$'),
        ),
    ]
