# Generated by Django 2.1.15 on 2021-02-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210122_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='optionvalue',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
