# Generated by Django 2.1.15 on 2021-02-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210201_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDomesticRawItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productcost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Product Cost C$')),
                ('baseproductsalesprice', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Base Product Sales Price C$')),
            ],
            options={
                'verbose_name': 'Domestic Raw Item',
                'verbose_name_plural': 'Domestic Raw Items',
                'db_table': 'tbl_domesticrawitems',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomesticProductRaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('productname', models.CharField(max_length=250)),
                ('markup', models.IntegerField(blank=True, default=35, null=True, verbose_name='Mark Up Rate(in %)')),
                ('firstcost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1st Cost China US$')),
                ('ldp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Landed Duty Paid')),
                ('printval', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Print')),
                ('totalcost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Cost')),
                ('productcostc', models.FloatField(blank=True, default=0.494, null=True, verbose_name='Product Cost C$')),
                ('targetgrossprofit', models.IntegerField(blank=True, default=33, null=True, verbose_name='Target Gross Profit (in %)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region')),
                ('subcatagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubCategory')),
                ('subsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SubSubCategory')),
            ],
            options={
                'verbose_name': 'Domestic(Raw) Product',
                'verbose_name_plural': 'Domestic(Raw) Products',
                'db_table': 'tbl_domesticrawproducts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DomesticProductRaw'),
        ),
    ]
