# Generated by Django 2.1.15 on 2021-02-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210211_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticproductraw',
            name='overhead',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.68, max_digits=5, null=True, verbose_name='Overhead'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='firstcost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.26, max_digits=5, null=True, verbose_name='1st Cost China US$'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='ldp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.43, max_digits=5, null=True, verbose_name='Landed Duty Paid'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='printval',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.63, max_digits=5, null=True, verbose_name='Print'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='totalcost',
            field=models.DecimalField(blank=True, decimal_places=2, default=2.74, max_digits=5, null=True, verbose_name='Total Cost'),
        ),
    ]
