# Generated by Django 2.1.15 on 2021-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210211_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='totalcost',
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='ldp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Landed Duty Paid'),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='overhead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Overhead'),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='printval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Print'),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='totalprecentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Percentage'),
        ),
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='1st Cost'),
        ),
    ]
