# Generated by Django 2.1.15 on 2021-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210211_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='baseproductsalesprice',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='productcost',
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='totalcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Cost'),
        ),
    ]
