# Generated by Django 2.1.15 on 2021-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210211_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticproductraw',
            name='packing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Packing'),
        ),
        migrations.AddField(
            model_name='domesticproductraw',
            name='printval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Print'),
        ),
        migrations.AddField(
            model_name='domesticproductraw',
            name='transfer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Transfer'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='broker',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Broker(in %)'),
        ),
    ]
