# Generated by Django 2.1.15 on 2021-02-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210212_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='1st Cost'),
        ),
    ]
