# Generated by Django 2.1.15 on 2021-02-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_adddomesticrawitem_marketval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='totalprecentage',
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='totallandedcost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Landed Cost'),
        ),
    ]
