# Generated by Django 2.1.15 on 2021-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210225_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='distributormargin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='marginonsell',
            field=models.IntegerField(),
        ),
    ]
