# Generated by Django 2.1.15 on 2021-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210225_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='distributormargin',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='listprice',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='marginonsell',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='adddomesticrawitem',
            name='onnetsell',
        ),
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
