# Generated by Django 2.1.15 on 2021-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210225_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='distributor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Distributor $$'),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='distributormargin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='listprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='List price'),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='marginonsell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='markup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddomesticrawitem',
            name='onnetsell',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='$$ On Net Sell Price'),
        ),
    ]
