# Generated by Django 2.1.15 on 2021-03-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210305_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticproductraw',
            name='firstcost',
            field=models.FloatField(blank=True, null=True, verbose_name='1st Cost China US$'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='overhead',
            field=models.FloatField(blank=True, default=33, null=True, verbose_name='Overhead(in %)'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='packing',
            field=models.FloatField(blank=True, null=True, verbose_name='Packing'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='printval',
            field=models.FloatField(blank=True, null=True, verbose_name='Print'),
        ),
        migrations.AlterField(
            model_name='domesticproductraw',
            name='transfer',
            field=models.FloatField(blank=True, null=True, verbose_name='Transfer'),
        ),
    ]
