# Generated by Django 2.1.15 on 2021-03-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210305_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='distributorcost',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=20, null=True, verbose_name='Disributor Cost'),
        ),
    ]
