# Generated by Django 3.1.2 on 2021-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210316_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='distributorcost',
            field=models.FloatField(blank=True, null=True, verbose_name='Distributor Cost'),
        ),
    ]
