# Generated by Django 2.1.15 on 2021-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210317_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticrawitem',
            name='markup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Markup (in %)'),
        ),
    ]
