# Generated by Django 2.1.15 on 2021-03-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210319_1013'),
        ('core', '0026_auto_20210319_1541'),
    ]

    operations = [
    ]
