# Generated by Django 2.2 on 2021-04-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210415_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddomesticsizeitem',
            name='size',
            field=models.ManyToManyField(blank=True, to='core.Size'),
        ),
    ]
