# Generated by Django 2.2 on 2021-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210416_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizePrice', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'tbl_sizeprice',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='adddomesticsizeitem',
            name='price',
        ),
        migrations.AddField(
            model_name='adddomesticsizeitem',
            name='price',
            field=models.ManyToManyField(blank=True, to='core.SizePrice'),
        ),
    ]
