# Generated by Django 2.2 on 2021-05-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210422_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticproductraw',
            name='fleece',
            field=models.FloatField(blank=True, null=True, verbose_name='Overhead(in %)'),
        ),
        migrations.AddField(
            model_name='domesticproductraw',
            name='sewing',
            field=models.FloatField(blank=True, null=True, verbose_name='Overhead(in %)'),
        ),
    ]
