# Generated by Django 3.2.3 on 2021-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210505_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='domesticproductraw',
            name='printedoutside',
            field=models.FloatField(blank=True, null=True, verbose_name='Printed Outside'),
        ),
    ]
